lib/main.dart
=> change title into Udang

constants/colors.dart, constants/spacing.dart, constants/text_styles.dart
Membuat constants untuk warna, spacing, dan textstyle
constant disini bisa digunakan untuk menerapkan style dan color palette yang sama untuk semua halaman
untuk sekarang, jika dirasa kesulitan untuk menggunakan constants, bisa tidak dipakai dulu, nanti bisa dipakai setelah refactoring
=> Add constants

lib/models/task_model.dart
**Add Task Models**
task model consist of id, task_name, task_desc, task_reminder, date, time, and progress.
=> add task models

lib/components/delete_confirmation_dialog.dart
dialog / pop up untuk konfirmasi menghapus task
Latar belakang pop up / dialog cuman sebagai uji coba, bukan halaman latar asli dari dialog ini
=> adding delete_confirmation_dialog.dart

lib/components/edit_task_bottom_sheet.dart, lib/pages/detail_group_page.dart
Fungsi delete dan dummy edittask
menambahkan delete di edit task dan menyambungkan dgn pop up delete konfirmasi. 
Menambahkan data dummy dari models agar tersambung sama data yg ada di group detail page.
=> tambahkan delete dan data dummy edittask

lib/models/task_model.dart
Kemarin ada atribut yang kurang di task models, yaitu task_group_id
=> add attribute task_group_id

lib/db/task_db_helper.dart
=> add task group id for db helper

lib/components/add_task_bottom_sheet.dart, lib/components/calendar.dart, lib/components/edit_task_bottom_sheet.dart, lib/components/task_card.dart, lib/components/task_group_card.dart, lib/db/db_provider.dart, lib/db/task_db_helper.dart, lib/main.dart, lib/models/task_model.dart, lib/pages/add_group_page.dart, lib/pages/detail_group_page.dart, lib/pages/task_group_page.dart, pubspec.yaml
Mengintegrasikan aplikasi ke database, sehingga fungsional aplikasi bisa dijalankan, + beberapa adjustment
- add fungsional untuk task_group_page
- add fungsional untuk add_task_page (create & update)
- adjustment DB
- add fungsional untuk modal add task & edit task
- beberapa minor fix untuk components
package sqflite_ffi aku hapus soalnya mengacaukan database
=> Add Functional + Few minor changes

lib/components/add_task_bottom_sheet.dart, lib/components/delete_confirmation_dialog.dart, lib/components/edit_task_bottom_sheet.dart, lib/db/task_db_helper.dart, lib/pages/detail_group_page.dart
buat fungsional untuk delete task
menambahkan fitur yang berhubungan dengan delete task termasuk teks snackbar yang berbeda
ada perubahan placeholder untuk deadline saat add task
=> Add delete task function

lib/components/add_task_bottom_sheet.dart, lib/components/edit_task_bottom_sheet.dart, lib/components/home_task_card.dart, lib/db/db_provider.dart, lib/db/task_db_helper.dart, lib/models/task_model.dart, lib/pages/detail_group_page.dart, lib/pages/home_page.dart
melengkapi komponen untuk home task card
meneysuaikan task model & helper (remove attribute reminder)
Menambahkan informasi task group di home task card
karena reminder di drop, model, dan helper termasuk provider dihilangkan atribut remindernya
=> fix home task card, adjust task model & helper

lib/pages/edit_group_page.dart
Merapikan beberapa kode, menambah addListener untuk description
=> Menambah addListener untuk description

lib/components/add_task_bottom_sheet.dart, lib/components/bottom_navigation_bar.dart, lib/components/edit_task_bottom_sheet.dart, lib/db/db_provider.dart, lib/pages/add_group_page.dart, lib/pages/detail_group_page.dart, lib/pages/home_page.dart
minor fixing beberapa yang masih miss, + beberapa snackbar masih pake indo, udah ganti pake inggris
=> final commits!!

lib/components/task_group_card.dart, pubspec.yaml
Task Group Card : fixing layout, title, description, information, last updated
Mengubah layouting statis menjadi dinamis
Tambahkan context apapun dari PR-mu. Opsional, tapi kalo perlu bisa ditambahkan, contohnya "menambahkan dependencies baru: ..."
=> fixing layout, title, description, information, last updated

lib/components/add_task_bottom_sheet.dart, lib/components/bottom_navigation_bar.dart, lib/components/calendar.dart, lib/components/delete_confirmation_dialog.dart, lib/components/edit_group_option.dart, lib/components/edit_task_bottom_sheet.dart, lib/components/marquee.dart, lib/components/task_group_card.dart, lib/constants/app_string.dart, lib/constants/colors.dart, lib/constants/length.dart, lib/db/task_group_db_helper.dart, lib/main.dart, lib/pages/add_group_page.dart, lib/pages/detail_group_page.dart, lib/pages/edit_group_page.dart, lib/pages/task_group_page.dart
Menambahkan ellipsis dan marquee.
- Marquee untuk animasi masih perlu fixing lagi ternyata, *nantikan pull request selanjutnya.*
- Ellipsis untuk edit task group dan delete group, *kurang snackbarnya nantikan juga pull request selanjutnya*
- delete confirmation groupnya udah bener. 
- nambahin file length dart
- calendar ngecilin font dan fontweightnya
- mbenerin edit group task nambahin karakter counter
- mbenerin doko di bottom navigator jadi app
- mbenerin index yang ada di bottom navigator biar bener karena salah dari 1 jadi 2
- mbenerin warna searchbarnya
- tutorial menyusul... pull request ketujuh
- Masih ada kesalahan di detailgroup page dengan yang main asli. mohon di cek aku lupa ngasih popscope
aku minta tolong kasih pass mergingnya jorj plisss, nanti tak check punyaku aja.
ini …
=> commit ke 6

lib/components/notification_card.dart, lib/pages/notification_page.dart
add notification_page.dart and notification_card.dart
membuat page notification dan component card notifikation
=> add notification page and card

lib/pages/task_group_page.dart
Fitur ascending/descending berdasarkan name atau default, sorting default di stel di ascending
Tambahkan context apapun dari PR-mu. Opsional, tapi kalo perlu bisa ditambahkan, contohnya "menambahkan dependencies baru: ..."
=> menambahkan fitur sorting ascending/descending

lib/components/add_task_modal.dart
Buat inputan attachment jadi link dgn regex
yg berubah ada pada on changed di attachment dan on pressed untuk validasi link sebelum disimpan
-
=> Validasi link

lib/components/bottom_navigation_bar.dart, lib/components/edit_task_bottom_sheet.dart, lib/db/db_provider.dart, lib/pages/detail_group_page.dart
Mengatur posisi item yang di dalam task card sesuai gambar yang disepakati
Banyak Menyimpan Perubahan dari main
=> Memperbaiki Task Card

lib/components/task_card.dart, lib/models/task_model.dart, pubspec.yaml
Menambahkan dan menyambungkan Link input user ke icon link
Menambahkan dependencies link di pubspec.yaml
Menambahkan final link pada task_model.dart
Menyambungkan icon link dgn link input user di task_card.dart
-
=> tambah hyperlink

lib/db/db_provider.dart, lib/db/focus_timer_db_helper.dart, lib/models/focus_timer_model.dart
Menambahkan model, database, dan CRUD Focus Timer.
- db provider -> di akhir, create table focus_timer
- focus_timer_db_helper -> CRUD focus timer  
- focus_timer_models -> model focus_timer
=> add focus timer database

android/app/src/main/AndroidManifest.xml, lib/components/add_task_modal.dart, lib/components/edit_task_bottom_sheet.dart, lib/components/task_card.dart, lib/pages/add_group_page.dart, lib/pages/task_group_page.dart
Benerin button launch URL kemarin ngga muncul karena pakai `task.attachment`, harusnya pakai `task.task_attachment`
Buatin Border buat button launch URL biar keliatan click area nya
Nambahin AndroidManifest supaya bisa buka URL diluar app
Benerin flow untuk add group
Benerin button launch URL kemarin ngga muncul karena pakai `task.attachment`, harusnya pakai `task.task_attachment`
Buatin Border buat button launch URL biar keliatan click area nya
Nambahin AndroidManifest supaya bisa buka URL diluar app
dulu kalo nambahin group dari TaskGroupPage > AddGroupPage > balik TaskGroupPage, klik Group yang mau dibuka > DetailGroupPage
sekarang dari AddGroupPage > DetailGroupPage dari group yang baru dibuat, kalo pop balik ke TaskGroupPage dan tentunya refresh group yang ditampilin
- ngubah …
=> Fix URL launch in task card + fix add group flow

lib/components/mode_card.dart, lib/models/focus_timer_model.dart, lib/pages/edit_focus_mode.dart
Jelaskan garis besar dari perubahan yang kalian buat, contohnya "Buat Calender component"
Berikan penjelasan lebih detail mengenai perubahan yang ada dalam PR. Jelaskan apapun yang terkait dengan perubahan yang kalian buat. Ngga perlu panjang-panjang banget kok, yang penting cukup jelas
Tambahkan context apapun dari PR-mu. Opsional, tapi kalo perlu bisa ditambahkan, contohnya "menambahkan dependencies baru: ..."
=> changing all 'sections' into 'intervals'
